CREATE SEQUENCE ALBUM_RECORDINGS_Sequence
START WITH 100
INCREMENT BY 1
MINVALUE 100
MAXVALUE 1000
NOCYCLE;

CREATE SEQUENCE ALBUMS_Sequence
START WITH 100
INCREMENT BY 1
MINVALUE 100
MAXVALUE 1000
NOCYCLE;

CREATE SEQUENCE ARTIST_ALBUM_Sequence
START WITH 100
INCREMENT BY 1
MINVALUE 100
MAXVALUE 1000
NOCYCLE;

CREATE SEQUENCE ARTISTS_Sequence
START WITH 100
INCREMENT BY 1
MINVALUE 100
MAXVALUE 1000
NOCYCLE;

CREATE SEQUENCE GENRES_Sequence
START WITH 100
INCREMENT BY 1
MINVALUE 100
MAXVALUE 1000
NOCYCLE;

CREATE SEQUENCE RECORDING_GENRE_Sequence
START WITH 100
INCREMENT BY 1
MINVALUE 100
MAXVALUE 1000
NOCYCLE;

CREATE SEQUENCE RECORDINGS_Sequence
START WITH 100
INCREMENT BY 1
MINVALUE 100
MAXVALUE 1000
NOCYCLE;
